# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53985fc5eab7b465aaa1c67dd198c87ee1a713b71c67e73fffef9854042c62e4bf0e8843f35c8b23089883eff2091a3394d664c9b27609ccc5ec8a3576eb8d43

test:
  secret_key_base: 1cf48278edc1f44f73513a9407b1051d5b021c42e82ae83936324a9b20d9a03e11a043e1bfff779dcfcbbb4c7fa3b55d9e5f89715e14e759fbb21f30fe510ca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
